default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: pai_auth_dev

test:
  <<: *default
  database: pai_auth_test

production:
  <<: *default
  adapter: mysql2
  username: <%= ENV['PAI_AUTH_USERNAME'] %>
  password: <%= ENV['PAI_AUTH_PASSWORD'] %>
  host: <%= ENV['PAI_AUTH_HOST'] %>
  database: <%= ENV['PAI_AUTH_DATABASE'] %>
